name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  email_auth: ^2.0.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/Backgrounds/
    - assets/ads/
